### ISSUE TITLE
[FEAT] Add a "results retrieved in x seconds" thingy

### ISSUE THREAD

**Issue by k4lizen** [hearchco/frontend#149]
^ that
![image](https://github.com/hearchco/frontend/assets/124312252/511d3b81-eea5-454a-82df-4a47455cc804)
![image](https://github.com/hearchco/frontend/assets/124312252/e791c3d3-0173-494b-a704-9f6d2f67f7de)
Something like this.

**Comment by aleksasiriski** [comment]
Should also be implemented on backend and returned with results, that way we could calculate on frontend how much time was spent actually searching and how much was latency between frontend and backend. I think we should display both things (probably display the frontend time and when hovered over display a hint for backend time and the delta)

**Comment by matijakljajic** [comment]
> Should also be implemented on backend and returned with results, that way we could calculate on frontend how much time was spent actually searching and how much was latency between frontend and backend. I think we should display both things (probably display the frontend time and when hovered over display a hint for backend time and the delta)

It would also be cool if it said how much engines did the search query use (I just saw that it's kind of implemented in LibreY). For example:
`Fetched 2.000.000.000 results in 0.61 seconds across 12 engines.`

**Comment by aleksasiriski** [comment]
> It would also be cool if it said how much engines did the search query use (I just saw that it's kind of implemented in LibreY). For example: `Hearched 2.000.000.000 results in 0.61 seconds across 12 engines.`

Should the number of engines be the one from the category (how many engines were being searched, which means that they might never return results if down or too slow) or should it be the number of engines that actually returned results?

The former should be returned from backend for each category (it can be easily done), whereas the latter can be done on either side (preferrably on backend too). Probably answered my own question, we should do both!
