### ISSUE TITLE
[BUG] semicolon breaks search

### ISSUE THREAD

**Issue by aleksasiriski** [hearchco/frontend#174]
Moved from [here](https://github.com/hearchco/hearchco/issues/264)

https://hearch.co/search?q=anything%3B
Nothing is retrieved

**Comment by matijakljajic** [comment]
@aleksasiriski Why isn't this issue transferred to the backend repo?

**Comment by aleksasiriski** [comment]
It also seems to be a bug with vercel adapter, but since we moved to our own AWS adapter it's working now!
