### ISSUE TITLE
[FEAT] Some sort of loading/transition animation on switching previewed image 

### ISSUE THREAD

**Issue by k4lizen** [hearchco/frontend#184]
Currently, if some image is being previewed, and another image is clicked, the new image can take some time to load, and during that time the old image will be present for the whole duration of the load. This is not good UX since its unclear to the user if the click actually registered.

A proposed solution could be that the old image fades out while the new one is loading, or be replaced with a loading animation, or both. Though since the title/description changes instantly, care should be taken that this makes sense.

**Comment by aleksasiriski** [comment]
I've already started work on this a week ago, it's a WIP.

**Comment by aleksasiriski** [comment]
This isn't an issue anymore, sicne we use thumbnail images for preview which are already loaded.
