### ISSUE TITLE
[FEAT] Shortcut to focus search query field

### ISSUE THREAD

**Issue by k4lizen** [hearchco/frontend#352]
The key `/` is commonly used to focus a search bar (google, ddg, brave, github), it would be neat if we had this feature too. 

Also, focusing the search query field (but not loading the suggestions until something is typed) when the results are loaded could be neat for when the query clearly needs to be edited. i.e. I want to be able to type instantly when the results are loaded, without pressing a shortcut or clicking on the field. Not sure if this is possible/generally desirable though.

**Comment by aleksasiriski** [comment]
> Also, focusing the search query field (but not loading the suggestions until something is typed) when the results are loaded could be neat for when the query clearly needs to be edited. i.e. I want to be able to type instantly when the results are loaded, without pressing a shortcut or clicking on the field. Not sure if this is possible/generally desirable though.

Are you talking about how the searchbox currently behaves on the homepage? If so, I deliberately disabled that for the results page because on phones focus on the searcbox means bringing up the keyboard and IMO it isn't a good UX if half the page is immediately taken up by your virtual keyboard.

**Comment by k4lizen** [comment]
A that makes sense! I didn't think of that
