### ISSUE TITLE
[FEAT] Add support for engine.Options

### ISSUE THREAD

**Issue by k4lizen** [hearchco/frontend#93]
https://github.com/hearchco/agent/blob/main/src/search/engines/options/structs.go

Some / all of these options should be configurable through the UI.

**Comment by aleksasiriski** [comment]
I don't see a reasonable place to ask users for "max pages". "page" (indicating from which to start) is supported via Paginator and InfiniteLoading components at the bottom.

As for Locale and SafeSearch, that should be part of #186
